ARG UBUNTU_RELEASE=22.04
ARG USER=ubuntu UID=101 GROUP=ubuntu GID=101
ARG CHISEL_VERSION=0.9.0

FROM ubuntu:$UBUNTU_RELEASE AS builder
ARG USER UID GROUP GID TARGETARCH UBUNTU_RELEASE CHISEL_VERSION
SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates git \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

ADD "https://github.com/canonical/chisel/releases/download/v${CHISEL_VERSION}/chisel_v${CHISEL_VERSION}_linux_${TARGETARCH}.tar.gz" chisel.tar.gz
RUN tar -xvf chisel.tar.gz -C /usr/bin/

RUN mkdir -p /rootfs/etc \
    && echo "$GROUP:x:$GID:" >/rootfs/etc/group \
    && echo "$USER:x:$UID:$GID::/nohome:/noshell" >/rootfs/etc/passwd

### BOILERPLATE END ###

RUN chisel cut --root /rootfs \
    base-files_base \
    base-files_release-info \
    tzdata_zoneinfo \
    ca-certificates_data \
    libc-bin_nsswitch \
    libgcc-s1_libs \
    libc6_libs \
    libssl3_libs \
    openssl_config

FROM scratch
ARG USER UID GROUP GID
COPY --from=builder /rootfs /
