#!/bin/bash
set -ex

echo "Running tests..."

export BASE_IMAGE=${1:-"ubuntu/chiselled-base:test"}
export BASE_SSL_IMAGE=${2:-"ubuntu/chiselled-base-ssl:test"}

compile_c() {
	gcc $1 -o app $2
}

compile_go() {
	go build -o app $2 $1
}

compile_rust() {
	cargo build
	cp ./target/debug/app .
	cargo clean
}

run_container() {
	docker run --rm -v $PWD/app:/app:ro $2 $1 /app
}

export -f compile_c
export -f compile_go
export -f compile_rust
export -f run_container

CURRENT_DIR="$(dirname $(readlink -f $0))"

for test_dir in "$CURRENT_DIR"/*/
do
    pushd $test_dir

    ./runtest

    popd
done
