name: "Canonical CLA Check"

on:
  pull_request:
    branches: [main]

jobs:
  cla-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v2
